document.addEventListener("DOMContentLoaded", () => {
    
    // --- 0. UTILITIES & LOGGING ---
    const consoleOut = document.getElementById('consoleOutput');
    
    function logToConsole(msg, type='normal') {
        if (!consoleOut) return;
        
        // 🔑 Smart Auto-Scroll
        const isScrolledToBottom = consoleOut.scrollHeight - consoleOut.clientHeight <= consoleOut.scrollTop + 50;

        const now = new Date();
        const timeStr = now.toLocaleTimeString('th-TH', { hour12: false });
        const line = document.createElement('div');
        line.className = 'log-line';
        line.style.color = type === 'error' ? '#ef4444' : (type === 'success' ? '#86efac' : '#ccc');
        line.innerHTML = `<span class="log-time">[${timeStr}]</span>${msg}`;
        consoleOut.appendChild(line);

        if (isScrolledToBottom) {
            consoleOut.scrollTop = consoleOut.scrollHeight;
        }
    }

    // --- 1. INITIALIZATION ---
    let socket = null;
    try {
        if (typeof io !== 'undefined') {
            socket = io();
            logToConsole("System Ready. Socket initialized.", "normal");
        } else {
            logToConsole("WARNING: Socket.io library not loaded. Backend connection disabled.", "error");
        }
    } catch(e) {
        logToConsole(`Socket Init Error: ${e}`, "error");
    }

    const widgetInstances = {}; 
    let grid = null;
    
    // 🔑 GRID CONFIGURATION (ป้องกันลากหลุดแล้วหาย)
    try {
        grid = GridStack.init({
            float: true,
            animate: true,
            cellHeight: 100,
            minRow: 1,
            margin: 8,
            column: 12,
            disableOneColumnMode: true,
            removable: false, // ❌ ห้ามลบ Widget โดยการลากออกนอกพื้นที่ (ต้องกดปุ่มลบใน Setting เท่านั้น)
            draggable: { 
                handle: '.widget-header', 
                scroll: true, 
                appendTo: 'body'
            }
        });
        
        // เพิ่ม Event Listener เช็คตอนลากเข้ามา
        grid.on('added', function(e, items) {
            // โค้ดนี้ทำงานเมื่อมี Widget ใหม่ถูกเพิ่มเข้ามา (จาก Sidebar)
            // ซึ่งปกติ GridStack จะจัดการให้เองว่าถ้าปล่อยนอก Grid จะไม่เพิ่ม
        });

    } catch(e) { logToConsole("GridStack Error: " + e, "error"); }

    // Database Variables
    let db = null;
    let SQL = null;
    let isDbRecording = false;
    let currentDbFileName = ""; 
    let fileHandle = null; 
    let isAutoGenerated = true;

    // Load SQL.js
    if(typeof initSqlJs !== 'undefined') {
        const configSql = { locateFile: filename => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.8.0/${filename}` };
        initSqlJs(configSql).then(function(sql) {
            SQL = sql;
            logToConsole("Database Engine Loaded.", "normal");
        });
    } else {
        logToConsole("Critical: SQL.js library missing.", "error");
    }

    // --- 2. HELPER FUNCTIONS ---
    const createWidgetHTML = (title, type, config = {}) => {
        const configStr = JSON.stringify(config);
        let label = "ID: -";
        if (type === 'Text') label = "Format Based";
        else if(config.indexes && config.indexes.length > 0) label = `ID: ${config.indexes.join(',')}`;

        const lockedIcon = config.locked ? 'fa-lock' : 'fa-lock-open';
        const lockedClass = config.locked ? 'locked' : '';

        return `
            <div class="widget-header">
                <span class="widget-title">${title}</span>
                <div class="widget-controls">
                    <button class="widget-lock-btn ${lockedClass}" title="Lock/Unlock"><i class="fa-solid ${lockedIcon}"></i></button>
                    <button class="widget-settings-btn" title="Settings"><i class="fa-solid fa-gear"></i></button>
                </div>
            </div>
            <div class="widget-body" data-type="${type}" data-config='${configStr}'>
                <div class="content-area" style="width:100%; height:100%; display:flex; justify-content:center; align-items:center;">NaN</div>
                <div class="widget-index-label">${label}</div>
            </div>
        `;
    };

    const createGridStackItem = (title, type, config, w = 3, h = 2, isLocked = false) => {
        const el = document.createElement('div');
        el.classList.add('grid-stack-item');
        el.setAttribute('gs-w', w);
        el.setAttribute('gs-h', h);
        
        if (isLocked) {
            el.setAttribute('gs-no-move', 'true');
            el.setAttribute('gs-no-resize', 'true');
            el.setAttribute('gs-locked', 'true');
        }

        el.innerHTML = `<div class="grid-stack-item-content">${createWidgetHTML(title, type, config)}</div>`;
        return el;
    };

    function downloadFile(content, fileName, mimeType) {
        const a = document.createElement('a');
        mimeType = mimeType || "application/octet-stream";
        if (content instanceof Uint8Array) {
            const blob = new Blob([content], {type: mimeType});
            a.href = URL.createObjectURL(blob);
        } else {
            a.href = `data:${mimeType};charset=utf-8,${encodeURIComponent(content)}`;
        }
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    }

    // --- 3. LAYOUT MANAGER ---
    const btnSaveLayout = document.getElementById('btnSaveLayout');
    const btnLoadLayout = document.getElementById('btnLoadLayout');
    const fileInputLayout = document.getElementById('fileInputLayout');

    btnSaveLayout.addEventListener('click', () => {
        const layoutData = [];
        grid.engine.nodes.forEach(node => {
            const el = node.el;
            const title = el.querySelector('.widget-title').innerText;
            const body = el.querySelector('.widget-body');
            let config = {};
            try { config = JSON.parse(body.dataset.config || '{}'); } catch(e) {}
            
            const isLocked = grid.getGridItems().find(item => item === el)?.gridstackNode?.noMove || false;
            config.locked = isLocked;

            layoutData.push({ x: node.x, y: node.y, w: node.w, h: node.h, title: title, type: body.dataset.type, config: config });
        });
        downloadFile(JSON.stringify(layoutData, null, 2), "dashboard_layout.json", "text/json");
        logToConsole("Layout saved.", "success");
    });

    btnLoadLayout.addEventListener('click', () => fileInputLayout.click());

    fileInputLayout.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (ev) => {
            try {
                const layoutData = JSON.parse(ev.target.result);
                grid.removeAll();
                layoutData.forEach(item => {
                    const isLocked = item.config?.locked || false;
                    const widgetEl = createGridStackItem(item.title, item.type, item.config, item.w, item.h, isLocked);
                    const newItem = grid.addWidget(widgetEl, { x: item.x, y: item.y });
                    if(isLocked) grid.update(newItem, { noMove: true, noResize: true });
                });
                logToConsole(`Loaded layout: ${file.name}`, 'success');
            } catch (err) { logToConsole(`Layout Error: ${err}`, 'error'); }
        };
        reader.readAsText(file);
        fileInputLayout.value = ''; 
    });

    // --- 4. LOCK LOGIC ---
    document.querySelector('.grid-stack').addEventListener('click', (e) => {
        const lockBtn = e.target.closest('.widget-lock-btn');
        if (lockBtn) {
            const widgetEl = lockBtn.closest('.grid-stack-item');
            const icon = lockBtn.querySelector('i');
            const isLocked = widgetEl.gridstackNode.noMove || false;
            if (isLocked) {
                grid.update(widgetEl, { noMove: false, noResize: false });
                icon.className = 'fa-solid fa-lock-open';
                lockBtn.classList.remove('locked');
            } else {
                grid.update(widgetEl, { noMove: true, noResize: true });
                icon.className = 'fa-solid fa-lock';
                lockBtn.classList.add('locked');
            }
        }
    });

    // --- 5. MODAL LOGIC ---
    const modalOverlay = document.getElementById('settingModalOverlay');
    const dynamicArea = document.getElementById('modal-dynamic-inputs');
    const inputName = document.getElementById('modalWidgetName');
    const selectType = document.getElementById('modalWidgetType');
    let currentEditingWidget = null;

    window.toggleMaxInput = (checkbox) => {
        const input = document.getElementById('inp-max-points');
        if (input) {
            input.disabled = checkbox.checked;
            if(checkbox.checked) input.classList.add('input-disabled');
            else input.classList.remove('input-disabled');
        }
    };

    function renderModalInputs(type, currentConfig = {}) {
        dynamicArea.innerHTML = "";
        if (!currentConfig.indexes) currentConfig.indexes = ["0"];
        if (!currentConfig.format) currentConfig.format = "{0}";
        if (!currentConfig.maxPoints) currentConfig.maxPoints = 20;
        const isUnlimit = currentConfig.isUnlimited === true;

        if (type === 'Text') {
            dynamicArea.innerHTML += `<div class="form-group-stack"><label class="modal-label-sm">Data Format</label><span class="helper-text">Format: {0}, {1}... use \\n for new line.</span><textarea id="inp-format" rows="3" style="height:auto;">${currentConfig.format}</textarea></div>`;
        } 
        else if (type === 'Graph') {
            const idxY = currentConfig.indexes[1] || currentConfig.indexes[0] || "0"; 
            const checkedAttr = isUnlimit ? 'checked' : '';
            const disabledAttr = isUnlimit ? 'disabled' : '';
            const disabledClass = isUnlimit ? 'input-disabled' : '';
            dynamicArea.innerHTML += `<div class="form-group-stack"><label class="modal-label-sm">Y-Axis Index</label><input type="number" id="inp-y" value="${idxY}" placeholder="0"></div><div class="form-group-stack"><label class="modal-label-sm">Max Data Points</label><div class="input-group-row"><input type="number" id="inp-max-points" value="${currentConfig.maxPoints}" ${disabledAttr} class="${disabledClass}"><label class="checkbox-label"><input type="checkbox" id="chk-unlimit" ${checkedAttr} onchange="toggleMaxInput(this)"> Unlimited</label></div></div>`;
        }
        else if (type === 'Map') {
            const lat = currentConfig.indexes[0] || "0";
            const lng = currentConfig.indexes[1] || "1";
            dynamicArea.innerHTML += `<div class="dynamic-row"><label style="width:40px;">Lat:</label><input type="number" id="inp-lat" value="${lat}"></div><div class="dynamic-row"><label style="width:40px;">Lng:</label><input type="number" id="inp-lng" value="${lng}"></div>`;
        }
        else if (type === 'Table') {
            dynamicArea.innerHTML += `<div id="table-rows-container"></div><button class="btn-add-row" onclick="addTableRow()">+ Add Row</button>`;
            if(!currentConfig.tableRows) currentConfig.tableRows = [{label: "Data", idx: "0"}];
            setTimeout(()=>currentConfig.tableRows.forEach(row => addTableRow(row.label, row.idx, document.getElementById('table-rows-container'))), 0);
        }
    }

    window.addTableRow = (label = "Data", idx = "0", targetContainer = null) => {
        const container = targetContainer || document.getElementById('table-rows-container');
        if(!container) return;
        const div = document.createElement('div');
        div.className = 'dynamic-row';
        div.innerHTML = `<input type="text" class="inp-table-label" value="${label}" placeholder="Label"><input type="number" class="inp-table-index" value="${idx}" placeholder="Idx" style="width:80px;"><button class="btn-icon-sm" onclick="this.parentElement.remove()"><i class="fa-solid fa-minus"></i></button>`;
        container.appendChild(div);
    }

    window.openModal = function(widgetElement) {
        currentEditingWidget = widgetElement;
        const header = widgetElement.querySelector('.widget-title');
        const body = widgetElement.querySelector('.widget-body');
        inputName.value = header.innerText;
        const type = body.dataset.type;
        selectType.value = type;
        let config = {};
        try { config = JSON.parse(body.dataset.config || '{}'); } catch(e) {}
        renderModalInputs(type, config);
        modalOverlay.classList.add('active');
    }

    function closeModal() {
        if (currentEditingWidget) {
            const header = currentEditingWidget.querySelector('.widget-title');
            const body = currentEditingWidget.querySelector('.widget-body');
            const type = selectType.value;
            const oldType = body.dataset.type;
            const newConfig = { indexes: [] };

            if (type === 'Text') {
                const fmt = document.getElementById('inp-format');
                if(fmt) newConfig.format = fmt.value;
            } 
            else if (type === 'Graph') {
                const y = document.getElementById('inp-y');
                const max = document.getElementById('inp-max-points');
                const chk = document.getElementById('chk-unlimit');
                newConfig.indexes.push('time'); 
                if(y) newConfig.indexes.push(y.value);
                if(max) newConfig.maxPoints = parseInt(max.value) || 20;
                if(chk) newConfig.isUnlimited = chk.checked;
            } 
            else if (type === 'Map') {
                const lat = document.getElementById('inp-lat');
                const lng = document.getElementById('inp-lng');
                if(lat) newConfig.indexes.push(lat.value);
                if(lng) newConfig.indexes.push(lng.value);
            } 
            else if (type === 'Table') {
                newConfig.tableRows = [];
                const labels = document.querySelectorAll('.inp-table-label');
                const idxs = document.querySelectorAll('.inp-table-index');
                labels.forEach((lbl, i) => {
                    newConfig.tableRows.push({ label: lbl.value, idx: idxs[i].value });
                    newConfig.indexes.push(idxs[i].value);
                });
            }

            const oldConfig = JSON.parse(body.dataset.config || '{}');
            newConfig.locked = oldConfig.locked || false;

            const wId = body.getAttribute('id');
            if (oldType === 'Graph' && type === 'Graph' && widgetInstances[wId]) {
                const chartInstance = widgetInstances[wId];
                if(chartInstance && chartInstance.data) {
                    body.preservedChartData = {
                        labels: chartInstance.data.labels,
                        datasets: chartInstance.data.datasets
                    };
                }
            }

            header.innerText = inputName.value;
            body.dataset.type = type;
            body.dataset.config = JSON.stringify(newConfig);

            let label = "ID: -";
            if (type === 'Text') label = "Format Based";
            else if(newConfig.indexes.length > 0) label = `ID: ${newConfig.indexes.join(',')}`;
            body.innerHTML = `<div class="content-area" style="width:100%; height:100%; display:flex; justify-content:center; align-items:center;">Waiting...</div><div class="widget-index-label">${label}</div>`;
            if(wId && widgetInstances[wId]) {
                 if(widgetInstances[wId].destroy) widgetInstances[wId].destroy();
                 if(widgetInstances[wId].remove) widgetInstances[wId].remove(); 
                 delete widgetInstances[wId];
            }
        }
        modalOverlay.classList.remove('active');
        currentEditingWidget = null;
    }

    document.getElementById('btnCloseModal').addEventListener('click', closeModal);
    modalOverlay.addEventListener('click', (e) => { if (e.target === modalOverlay) closeModal(); });

    selectType.addEventListener('change', () => renderModalInputs(selectType.value, {}));
    document.getElementById('btnDeleteWidget').addEventListener('click', () => { if(currentEditingWidget) { grid.removeWidget(currentEditingWidget); closeModal(); } });
    
    document.querySelector('.grid-stack').addEventListener('click', (e) => {
        const btn = e.target.closest('.widget-settings-btn');
        if (btn) openModal(btn.closest('.grid-stack-item'));
    });

    document.getElementById('btnAddWidget').addEventListener('click', () => {
        const nameInp = document.getElementById('widget-name');
        const typeInp = document.getElementById('widget-type');
        let name = nameInp.value.trim() || "Untitled";
        const widgetEl = createGridStackItem(name, typeInp.value, {indexes:["0"], format:"{0}"}, 3, 2);
        grid.addWidget(widgetEl);
        nameInp.value = "";
    });

    document.getElementById('btnToggleSidebar').addEventListener('click', () => {
        document.getElementById('appContainer').classList.toggle('sidebar-closed');
        setTimeout(() => grid.onResize(), 300);
    });

    window.toggleSection = function(header) {
        header.classList.toggle('active');
        header.nextElementSibling.classList.toggle('open');
    }

    const inpName = document.getElementById('modalWidgetName');
    inpName.addEventListener('click', () => {
        if (inpName.hasAttribute('readonly')) {
            inpName.removeAttribute('readonly');
            inpName.classList.add('editable');
            inpName.focus(); inpName.select();
        }
    });
    const finishEditingName = () => {
        inpName.setAttribute('readonly', true);
        inpName.classList.remove('editable');
        inpName.blur(); 
    };
    inpName.addEventListener('blur', finishEditingName);
    inpName.addEventListener('keydown', (e) => { if(e.key === 'Enter') finishEditingName(); });

    // --- 7. DATABASE UI LOGIC (UPDATED) ---
    const btnNewDbFile = document.getElementById('btnNewDbFile');
    const btnOpenDbFile = document.getElementById('btnOpenDbFile');
    const dbPathText = document.getElementById('dbPathText');
    const dbClearBtn = document.getElementById('dbClearBtn');
    const btnConnectDb = document.getElementById('btnConnectDb');
    const dbFileInput = document.getElementById('dbFileInput');
    const dbInfoText = document.getElementById('dbInfoText');
    const dbWarningText = document.getElementById('dbWarningText');
    const dbPathBox = document.getElementById('dbPathBox');

    // 1. New File (Save As)
    btnNewDbFile.addEventListener('click', async () => {
        if (isDbRecording) return;
        
        if ('showSaveFilePicker' in window) {
            try {
                fileHandle = await window.showSaveFilePicker({
                    suggestedName: 'mission_log.sqlite',
                    types: [{
                        description: 'SQLite Database',
                        accept: {'application/x-sqlite3': ['.sqlite', '.db']},
                    }],
                });
                
                currentDbFileName = fileHandle.name;
                db = new SQL.Database();
                db.run("CREATE TABLE IF NOT EXISTS telemetry_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, raw_data TEXT);");

                isAutoGenerated = false; // User created file
                dbPathText.innerText = currentDbFileName;
                dbPathText.classList.add('has-file');
                dbPathBox.classList.add('has-file'); // 🔑 GLOW ON
                dbClearBtn.style.display = "block";
                btnConnectDb.disabled = false;
                btnConnectDb.innerText = "Start Recording";
                dbInfoText.innerText = "New file ready.";
                
                logToConsole(`File Created: ${currentDbFileName}`, "success");

            } catch (err) {
                if(err.name !== 'AbortError') logToConsole(`Action Cancelled`, "normal");
            }
        } else {
            alert("Your browser doesn't support direct file creation. Use Auto-Generate instead.");
        }
    });

    // 2. Open File (Open Picker)
    btnOpenDbFile.addEventListener('click', async () => {
        if (isDbRecording) return;

        if ('showOpenFilePicker' in window) {
            try {
                const [handle] = await window.showOpenFilePicker({
                    types: [{
                        description: 'SQLite Database',
                        accept: {'application/x-sqlite3': ['.sqlite', '.db']},
                    }],
                    multiple: false
                });
                
                const file = await handle.getFile();
                const arrayBuffer = await file.arrayBuffer();
                const uInt8Array = new Uint8Array(arrayBuffer);
                
                db = new SQL.Database(uInt8Array);
                fileHandle = handle; 
                currentDbFileName = file.name;
                isAutoGenerated = false; // User loaded file

                let rowCount = 0;
                try {
                    const res = db.exec("SELECT count(*) FROM telemetry_logs");
                    if(res.length > 0) rowCount = res[0].values[0][0];
                } catch(e) {}

                dbPathText.innerText = currentDbFileName;
                dbPathText.classList.add('has-file');
                dbPathBox.classList.add('has-file'); // 🔑 GLOW ON
                dbClearBtn.style.display = "block";
                btnConnectDb.disabled = false;
                btnConnectDb.innerText = "Start Recording (Append)";
                dbInfoText.innerText = `Loaded: ${rowCount} records`;
                
                logToConsole(`Opened: ${file.name}`, 'success');

            } catch (err) {
                if(err.name !== 'AbortError') logToConsole(`Action Cancelled`, "normal");
            }
        } else {
            dbFileInput.click(); // Fallback
        }
    });

    // Fallback Input
    dbFileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (file) {
            currentDbFileName = file.name;
            const reader = new FileReader();
            reader.onload = function() {
                try {
                    const uInt8Array = new Uint8Array(this.result);
                    db = new SQL.Database(uInt8Array); 
                    fileHandle = null; 
                    isAutoGenerated = false;
                    
                    dbPathText.innerText = file.name;
                    dbPathText.classList.add('has-file');
                    dbPathBox.classList.add('has-file'); // 🔑 GLOW ON
                    dbClearBtn.style.display = "block";
                    btnConnectDb.disabled = false;
                    btnConnectDb.innerText = "Start Recording (Append)";
                    dbInfoText.innerText = "Loaded (Fallback)";
                    
                    logToConsole(`Opened: ${file.name}`, 'normal');
                } catch(err) { logToConsole(`DB Load Error: ${err}`, 'error'); }
            }
            reader.readAsArrayBuffer(file);
        }
        dbFileInput.value = '';
    });

    // 3. Clear Button
    dbClearBtn.addEventListener('click', (e) => {
        e.stopPropagation(); 
        if (isDbRecording) return;
        
        db = null; fileHandle = null; currentDbFileName = ""; isAutoGenerated = true;
        
        dbPathText.innerText = "No file selected (Auto)";
        dbPathText.classList.remove('has-file');
        dbPathBox.classList.remove('has-file'); // 🔑 GLOW OFF
        dbClearBtn.style.display = "none";
        dbWarningText.style.display = "none"; 
        btnConnectDb.innerText = "Start Recording";
        dbInfoText.innerText = "Ready to Record";
        
        logToConsole("File selection cleared. Will auto-generate on start.", "normal");
    });

    // 🔑 3.1 Reveal File (Click Box -> Only if has file)
    dbPathBox.addEventListener('click', () => {
        if(isDbRecording) return;
        // ถ้าเป็น Auto-Generate (ยังไม่เลือกไฟล์) -> ไม่ทำอะไร
        if(isAutoGenerated) return;

        // ถ้ามีไฟล์เลือกอยู่แล้ว -> คลิกเพื่อเลือกใหม่ (หรือเสมือนเปิดดูโฟลเดอร์เดิม)
        btnOpenDbFile.click();
    });


    // 4. MAIN RECORD LOGIC
    btnConnectDb.addEventListener('click', async () => {
        if (!SQL) { logToConsole("SQL.js loading...", "error"); return; }

        if (!isDbRecording) {
            // --- START ---
            
            // Case A: No file selected -> Auto-Generate
            if (!db) {
                db = new SQL.Database();
                db.run("CREATE TABLE IF NOT EXISTS telemetry_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, raw_data TEXT);");
                
                const now = new Date();
                const ts = now.toISOString().slice(0,19).replace(/[:T]/g,'-');
                currentDbFileName = `log_${ts}.sqlite`;
                isAutoGenerated = true;
                
                dbPathText.innerText = currentDbFileName + " (Auto)";
                // Note: Auto-gen files are virtual, so we do NOT turn on 'has-file' glow
                logToConsole(`Auto-Created: ${currentDbFileName}`, "success");
            }

            isDbRecording = true;
            document.getElementById('dbStatusLed').classList.add('active');
            btnConnectDb.innerText = "Stop & Save";
            btnConnectDb.classList.add('stop-mode');
            
            // Disable buttons
            btnNewDbFile.disabled = true;
            btnOpenDbFile.disabled = true;
            dbClearBtn.style.display = "none";
            
            // 🔑 Show Warning ONLY if it's NOT auto-generated (User Opened/Selected File)
            if(!isAutoGenerated) {
                dbWarningText.style.display = "flex";
            } else {
                dbWarningText.style.display = "none";
            }

        } else {
            // --- STOP ---
            isDbRecording = false;
            document.getElementById('dbStatusLed').classList.remove('active');
            btnConnectDb.innerText = "Start Recording";
            btnConnectDb.classList.remove('stop-mode');
            
            // Hide Warning
            dbWarningText.style.display = "none";
            
            const binaryArray = db.export();

            // Save Logic
            if (fileHandle) {
                try {
                    const writable = await fileHandle.createWritable();
                    await writable.write(binaryArray);
                    await writable.close();
                    logToConsole(`Updated File: ${currentDbFileName}`, "success");
                } catch (err) {
                    logToConsole(`Save Failed: ${err}. Downloading backup...`, "error");
                    downloadFile(binaryArray, currentDbFileName, "application/x-sqlite3");
                }
            } else {
                // Auto-Generate or Fallback
                downloadFile(binaryArray, currentDbFileName, "application/x-sqlite3");
                logToConsole(`Downloaded: ${currentDbFileName}`, "success");
            }

            // Cleanup Logic
            if (isAutoGenerated) {
                db = null;
                dbPathText.innerText = "No file selected (Auto)";
                dbPathText.classList.remove('has-file');
                dbPathBox.classList.remove('has-file'); // Glow Off
                dbClearBtn.style.display = "none";
                dbInfoText.innerText = "Ready to Record";
                logToConsole("Auto-generated file saved & cleared.", "normal");
            } else {
                dbClearBtn.style.display = "block";
            }
            
            // Re-enable buttons
            btnNewDbFile.disabled = false;
            btnOpenDbFile.disabled = false;
        }
    });

    // CONNECT
    document.getElementById('btnConnect').addEventListener('click', () => {
        const port = document.getElementById('cfg-com').value;
        const baud = document.getElementById('cfg-baud').value;
        if(socket) {
            logToConsole(`Connecting to ${port}...`, "normal");
            socket.emit('connect_serial', { port: port, baud: baud });
        } else {
            logToConsole("Cannot connect: Socket is offline.", "error");
        }
    });

    const consoleInp = document.getElementById('consoleInput');
    // Socket Events
    if(socket) {
        socket.on('serial_data', (d) => {
            const raw = d.data;
            logToConsole(`RX: ${raw}`);
            updateDashboard(raw);
            if (isDbRecording && db) {
                try {
                    db.run("CREATE TABLE IF NOT EXISTS telemetry_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, raw_data TEXT);");
                    const stmt = db.prepare("INSERT INTO telemetry_logs (raw_data) VALUES (?)");
                    stmt.run([raw]);
                    stmt.free();
                } catch(e) { console.error(e); }
            }
        });
        socket.on('log_message', (d) => logToConsole(d.msg, d.type));
    }

    document.getElementById('btnSend').addEventListener('click', () => {
        const val = document.getElementById('sim-input').value;
        if(val.trim()) { logToConsole(`RX(Sim): ${val}`); updateDashboard(val); document.getElementById('sim-input').value = ""; }
    });

    consoleInp.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') {
            const cmd = consoleInp.value.trim();
            if (cmd) { 
                if(socket) socket.emit('send_command', { cmd: cmd }); 
                consoleInp.value = ""; 
            }
        }
    });
    
    document.getElementById('btnClearConsole').addEventListener('click', () => { if(consoleOut) consoleOut.innerHTML = ''; });

    // Resize Logic
    const consolePanel = document.getElementById('consolePanel');
    const consoleResizer = document.getElementById('consoleResizer');
    let isResizing = false, isDragging = false, startY = 0;
    
    if(consoleResizer) {
        consoleResizer.addEventListener('mousedown', (e) => { isResizing = true; isDragging = false; startY = e.clientY; document.body.style.cursor = 'row-resize'; e.preventDefault(); });
        document.addEventListener('mousemove', (e) => {
            if (!isResizing) return;
            if (Math.abs(e.clientY - startY) > 5) isDragging = true;
            if (isDragging) {
                let h = document.body.clientHeight - e.clientY;
                if (h < 50) { consolePanel.classList.add('collapsed'); document.documentElement.style.removeProperty('--console-height'); }
                else { consolePanel.classList.remove('collapsed'); if(h>600) h=600; document.documentElement.style.setProperty('--console-height', h + 'px'); }
            }
        });
        document.addEventListener('mouseup', () => {
            if (isResizing && !isDragging) {
                if (consolePanel.classList.contains('collapsed')) { consolePanel.classList.remove('collapsed'); document.documentElement.style.setProperty('--console-height', '180px'); }
                else { consolePanel.classList.add('collapsed'); document.documentElement.style.removeProperty('--console-height'); }
            }
            isResizing = false; isDragging = false; document.body.style.cursor = 'default';
        });
    }

    function updateDashboard(dataString) {
        const dataArray = dataString.split(',').map(s => s.trim());
        const widgets = document.querySelectorAll('.widget-body');

        widgets.forEach(widget => {
            const contentArea = widget.querySelector('.content-area');
            if(!contentArea) return;

            let config = {};
            try { config = JSON.parse(widget.dataset.config || '{}'); } catch(e) {}
            
            if (!widget.id) widget.id = 'w-' + Math.random().toString(36).substr(2, 9);
            const wId = widget.id;
            const type = widget.dataset.type;

            if (type === 'Text') {
                let text = config.format || "{0}";
                text = text.replace(/\{(\d+)\}/g, (match, index) => {
                    const i = parseInt(index);
                    return (!isNaN(i) && dataArray[i] !== undefined) ? dataArray[i] : "NaN";
                });
                contentArea.innerHTML = text.replace(/\\n/g, '<br>');
            }
            else if (type === 'Graph') {
                const idxY = parseInt(config.indexes[1] || "0");
                const valY = parseFloat(dataArray[idxY]);
                const maxPoints = parseInt(config.maxPoints) || 20;
                const isUnlimit = config.isUnlimited === true;
                
                if (!widgetInstances[wId]) {
                    contentArea.innerHTML = '<canvas></canvas>';
                    const ctx = contentArea.querySelector('canvas').getContext('2d');
                    let initData = { labels: [], datasets: [{ label: 'Data', data: [], borderColor: '#38bdf8', tension: 0.3, pointRadius: 0 }] };
                    if (widget.preservedChartData) {
                        initData.labels = widget.preservedChartData.labels;
                        initData.datasets = widget.preservedChartData.datasets;
                        delete widget.preservedChartData;
                    }
                    widgetInstances[wId] = new Chart(ctx, {
                        type: 'line', data: initData,
                        options: { responsive: true, maintainAspectRatio: false, animation: false, scales: { x: { display: false }, y: { grid: { color: 'rgba(255,255,255,0.1)' }, ticks: { color: '#fff' } } }, plugins: { legend: { display: false } } }
                    });
                }
                const chart = widgetInstances[wId];
                if (!isNaN(valY)) {
                    chart.data.labels.push(new Date().toLocaleTimeString());
                    chart.data.datasets[0].data.push(valY);
                    if (!isUnlimit) {
                        while (chart.data.labels.length > maxPoints) { 
                            chart.data.labels.shift(); chart.data.datasets[0].data.shift(); 
                        }
                    }
                    chart.update();
                }
            }
            else if (type === 'Map') {
                const lat = parseFloat(dataArray[parseInt(config.indexes[0])]);
                const lng = parseFloat(dataArray[parseInt(config.indexes[1])]);
                if (!widgetInstances[wId]) {
                    contentArea.innerHTML = '<div class="map-container" style="height:100%; width:100%;"></div>';
                    const map = L.map(contentArea.querySelector('.map-container'), { attributionControl: false }).setView([13.7563, 100.5018], 10);
                    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {}).addTo(map);
                    widgetInstances[wId] = { map, marker: L.marker([13.7563, 100.5018]).addTo(map) };
                    setTimeout(() => map.invalidateSize(), 500);
                }
                if (!isNaN(lat) && !isNaN(lng)) {
                    widgetInstances[wId].marker.setLatLng([lat, lng]);
                    widgetInstances[wId].map.panTo([lat, lng]);
                }
            }
            else if (type === 'Table') {
                 let html = `<table class="data-table" style="width:100%;"><thead><tr><th>Type</th><th>Data</th></tr></thead><tbody>`;
                 if(config.tableRows) {
                     config.tableRows.forEach(row => {
                         let val = dataArray[parseInt(row.idx)];
                         html += `<tr><td>${row.label}</td><td style="color:#38bdf8;">${val !== undefined ? val : "-"}</td></tr>`;
                     });
                 }
                 contentArea.innerHTML = `<div style="overflow-y:auto; max-height:100%; width:100%;">${html}</tbody></table></div>`;
            }
        });
    }
});